# fly.toml app configuration file generated for talapoin on 2025-03-15T17:18:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'talapoin'
primary_region = 'den'

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "litefs"
  destination = "/app/db"
